# Copyright (c) 2016 Akuli

# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:

# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

"""This is a Paste ofCode file for PasteTray.

Thanks to __Myst__ <https://github.com/SquishyStrawberry/> for making
the original pasting script. This script is my version of it.
"""

import requests
from pastetray import USER_AGENT

name = 'Paste ofCode'
url = 'http://paste.ofcode.org/'
use_syntax_colors = True
expiry_days = [7]
default_syntax = 'Text only'
syntax_choices = {
    # This was generated with syntax_getters/paste_ofcode.py in the
    # source package.
    'ABAP': 'abap',
    'ActionScript': 'as',
    'ActionScript 3': 'as3',
    'Ada': 'ada',
    'Agda': 'agda',
    'Alloy': 'alloy',
    'AmbientTalk': 'at',
    'ANTLR': 'antlr',
    'ANTLR With ActionScript Target': 'antlr-as',
    'ANTLR With C# Target': 'antlr-csharp',
    'ANTLR With CPP Target': 'antlr-cpp',
    'ANTLR With Java Target': 'antlr-java',
    'ANTLR With ObjectiveC Target': 'antlr-objc',
    'ANTLR With Perl Target': 'antlr-perl',
    'ANTLR With Python Target': 'antlr-python',
    'ANTLR With Ruby Target': 'antlr-ruby',
    'ApacheConf': 'apacheconf',
    'APL': 'apl',
    'AppleScript': 'applescript',
    'AspectJ': 'aspectj',
    'aspx-cs': 'aspx-cs',
    'aspx-vb': 'aspx-vb',
    'Asymptote': 'asy',
    'autohotkey': 'ahk',
    'AutoIt': 'autoit',
    'Awk': 'awk',
    'Base Makefile': 'basemake',
    'Bash': 'bash',
    'Bash Session': 'console',
    'Batchfile': 'bat',
    'BBCode': 'bbcode',
    'Befunge': 'befunge',
    'BlitzBasic': 'blitzbasic',
    'BlitzMax': 'blitzmax',
    'Boo': 'boo',
    'Brainfuck': 'brainfuck',
    'Bro': 'bro',
    'BUGS': 'bugs',
    'C': 'c',
    'C#': 'csharp',
    'C++': 'cpp',
    'c-objdump': 'c-objdump',
    'ca65 assembler': 'ca65',
    'CBM BASIC V2': 'cbmbas',
    'Ceylon': 'ceylon',
    'CFEngine3': 'cfengine3',
    'cfstatement': 'cfs',
    'ChaiScript': 'chai',
    'Chapel': 'chapel',
    'Cheetah': 'cheetah',
    'Cirru': 'cirru',
    'Clay': 'clay',
    'Clojure': 'clojure',
    'ClojureScript': 'clojurescript',
    'CMake': 'cmake',
    'COBOL': 'cobol',
    'COBOLFree': 'cobolfree',
    'CoffeeScript': 'coffee-script',
    'Coldfusion CFC': 'cfc',
    'Coldfusion HTML': 'cfm',
    'Common Lisp': 'common-lisp',
    'Coq': 'coq',
    'cpp-objdump': 'cpp-objdump',
    'Croc': 'croc',
    'Cryptol': 'cryptol',
    'CSS': 'css',
    'CSS+Django/Jinja': 'css+django',
    'CSS+Genshi Text': 'css+genshitext',
    'CSS+Lasso': 'css+lasso',
    'CSS+Mako': 'css+mako',
    'CSS+mozpreproc': 'css+mozpreproc',
    'CSS+Myghty': 'css+myghty',
    'CSS+PHP': 'css+php',
    'CSS+Ruby': 'css+erb',
    'CSS+Smarty': 'css+smarty',
    'CUDA': 'cuda',
    'Cypher': 'cypher',
    'Cython': 'cython',
    'D': 'd',
    'd-objdump': 'd-objdump',
    'Darcs Patch': 'dpatch',
    'Dart': 'dart',
    'Debian Control file': 'control',
    'Debian Sourcelist': 'sourceslist',
    'Delphi': 'delphi',
    'dg': 'dg',
    'Diff': 'diff',
    'Django/Jinja': 'django',
    'Docker': 'docker',
    'DTD': 'dtd',
    'Duel': 'duel',
    'Dylan': 'dylan',
    'Dylan session': 'dylan-console',
    'DylanLID': 'dylan-lid',
    'EBNF': 'ebnf',
    'eC': 'ec',
    'ECL': 'ecl',
    'Eiffel': 'eiffel',
    'Elixir': 'elixir',
    'Elixir iex session': 'iex',
    'Embedded Ragel': 'ragel-em',
    'ERB': 'erb',
    'Erlang': 'erlang',
    'Erlang erl session': 'erl',
    'Evoque': 'evoque',
    'Factor': 'factor',
    'Fancy': 'fancy',
    'Fantom': 'fan',
    'Felix': 'felix',
    'Fortran': 'fortran',
    'FoxPro': 'foxpro',
    'FSharp': 'fsharp',
    'GAP': 'gap',
    'GAS': 'gas',
    'Genshi': 'genshi',
    'Genshi Text': 'genshitext',
    'Gettext Catalog': 'pot',
    'Gherkin': 'cucumber',
    'GLSL': 'glsl',
    'Gnuplot': 'gnuplot',
    'Go': 'go',
    'Golo': 'golo',
    'GoodData-CL': 'gooddata-cl',
    'Gosu': 'gosu',
    'Gosu Template': 'gst',
    'Groff': 'groff',
    'Groovy': 'groovy',
    'Haml': 'haml',
    'Handlebars': 'handlebars',
    'Haskell': 'haskell',
    'Haxe': 'hx',
    'HTML': 'html',
    'HTML+Cheetah': 'html+cheetah',
    'HTML+Django/Jinja': 'html+django',
    'HTML+Evoque': 'html+evoque',
    'HTML+Genshi': 'html+genshi',
    'HTML+Handlebars': 'html+handlebars',
    'HTML+Lasso': 'html+lasso',
    'HTML+Mako': 'html+mako',
    'HTML+Myghty': 'html+myghty',
    'HTML+PHP': 'html+php',
    'HTML+Smarty': 'html+smarty',
    'HTML+Twig': 'html+twig',
    'HTML+Velocity': 'html+velocity',
    'HTTP': 'http',
    'Hxml': 'haxeml',
    'Hy': 'hylang',
    'Hybris': 'hybris',
    'IDL': 'idl',
    'Idris': 'idris',
    'Igor': 'igor',
    'Inform 6': 'inform6',
    'Inform 6 template': 'i6t',
    'Inform 7': 'inform7',
    'INI': 'ini',
    'Io': 'io',
    'Ioke': 'ioke',
    'IRC logs': 'irc',
    'Isabelle': 'isabelle',
    'Jade': 'jade',
    'JAGS': 'jags',
    'Jasmin': 'jasmin',
    'Java': 'java',
    'Java Server Page': 'jsp',
    'JavaScript': 'js',
    'JavaScript+Cheetah': 'js+cheetah',
    'JavaScript+Django/Jinja': 'js+django',
    'JavaScript+Genshi Text': 'js+genshitext',
    'JavaScript+Lasso': 'js+lasso',
    'JavaScript+Mako': 'js+mako',
    'Javascript+mozpreproc': 'javascript+mozpreproc',
    'JavaScript+Myghty': 'js+myghty',
    'JavaScript+PHP': 'js+php',
    'JavaScript+Ruby': 'js+erb',
    'JavaScript+Smarty': 'js+smarty',
    'JSON': 'json',
    'JSON-LD': 'jsonld',
    'Julia': 'julia',
    'Julia console': 'jlcon',
    'Kal': 'kal',
    'Kconfig': 'kconfig',
    'Koka': 'koka',
    'Kotlin': 'kotlin',
    'Lasso': 'lasso',
    'Lean': 'lean',
    'Lighttpd configuration file': 'lighty',
    'Limbo': 'limbo',
    'liquid': 'liquid',
    'Literate Agda': 'lagda',
    'Literate Cryptol': 'lcry',
    'Literate Haskell': 'lhs',
    'Literate Idris': 'lidr',
    'LiveScript': 'live-script',
    'LLVM': 'llvm',
    'Logos': 'logos',
    'Logtalk': 'logtalk',
    'LSL': 'lsl',
    'Lua': 'lua',
    'Makefile': 'make',
    'Mako': 'mako',
    'MAQL': 'maql',
    'Mask': 'mask',
    'Mason': 'mason',
    'Mathematica': 'mathematica',
    'Matlab': 'matlab',
    'Matlab session': 'matlabsession',
    'MiniD': 'minid',
    'Modelica': 'modelica',
    'Modula-2': 'modula2',
    'MoinMoin/Trac Wiki markup': 'trac-wiki',
    'Monkey': 'monkey',
    'MOOCode': 'moocode',
    'MoonScript': 'moon',
    'mozhashpreproc': 'mozhashpreproc',
    'mozpercentpreproc': 'mozpercentpreproc',
    'MQL': 'mql',
    'Mscgen': 'mscgen',
    'MuPAD': 'mupad',
    'MXML': 'mxml',
    'Myghty': 'myghty',
    'MySQL': 'mysql',
    'NASM': 'nasm',
    'Nemerle': 'nemerle',
    'nesC': 'nesc',
    'NewLisp': 'newlisp',
    'Newspeak': 'newspeak',
    'Nginx configuration file': 'nginx',
    'Nimrod': 'nimrod',
    'Nit': 'nit',
    'Nix': 'nixos',
    'NSIS': 'nsis',
    'NumPy': 'numpy',
    'objdump': 'objdump',
    'objdump-nasm': 'objdump-nasm',
    'Objective-C': 'objective-c',
    'Objective-C++': 'objective-c++',
    'Objective-J': 'objective-j',
    'OCaml': 'ocaml',
    'Octave': 'octave',
    'Ooc': 'ooc',
    'Opa': 'opa',
    'OpenEdge ABL': 'openedge',
    'Pan': 'pan',
    'Pawn': 'pawn',
    'Perl': 'perl',
    'Perl6': 'perl6',
    'PHP': 'php',
    'Pig': 'pig',
    'Pike': 'pike',
    'PL/pgSQL': 'plpgsql',
    'PostgreSQL console (psql)': 'psql',
    'PostgreSQL SQL dialect': 'postgresql',
    'PostScript': 'postscript',
    'POVRay': 'pov',
    'PowerShell': 'powershell',
    'Prolog': 'prolog',
    'Properties': 'properties',
    'Protocol Buffer': 'protobuf',
    'Puppet': 'puppet',
    'PyPy Log': 'pypylog',
    'Python': 'python',
    'Python 3': 'python3',
    'Python 3.0 Traceback': 'py3tb',
    'Python console session': 'pycon',
    'Python Traceback': 'pytb',
    'QBasic': 'qbasic',
    'QML': 'qml',
    'Racket': 'racket',
    'Ragel': 'ragel',
    'Ragel in C Host': 'ragel-c',
    'Ragel in CPP Host': 'ragel-cpp',
    'Ragel in D Host': 'ragel-d',
    'Ragel in Java Host': 'ragel-java',
    'Ragel in Objective C Host': 'ragel-objc',
    'Ragel in Ruby Host': 'ragel-ruby',
    'Raw token data': 'raw',
    'RConsole': 'rconsole',
    'Rd': 'rd',
    'REBOL': 'rebol',
    'Red': 'red',
    'Redcode': 'redcode',
    'reg': 'registry',
    'ResourceBundle': 'resource',
    'reStructuredText': 'rst',
    'Rexx': 'rexx',
    'RHTML': 'rhtml',
    'RobotFramework': 'robotframework',
    'RPMSpec': 'spec',
    'RQL': 'rql',
    'RSL': 'rsl',
    'Ruby': 'rb',
    'Ruby irb session': 'rbcon',
    'Rust': 'rust',
    'S': 'splus',
    'Sass': 'sass',
    'Scala': 'scala',
    'Scalate Server Page': 'ssp',
    'Scaml': 'scaml',
    'Scheme': 'scheme',
    'Scilab': 'scilab',
    'SCSS': 'scss',
    'Shell Session': 'shell-session',
    'Slim': 'slim',
    'Smali': 'smali',
    'Smalltalk': 'smalltalk',
    'Smarty': 'smarty',
    'Snobol': 'snobol',
    'SourcePawn': 'sp',
    'SPARQL': 'sparql',
    'SQL': 'sql',
    'sqlite3con': 'sqlite3',
    'SquidConf': 'squidconf',
    'Stan': 'stan',
    'Standard ML': 'sml',
    'Swift': 'swift',
    'SWIG': 'swig',
    'systemverilog': 'systemverilog',
    'TADS 3': 'tads3',
    'Tcl': 'tcl',
    'Tcsh': 'tcsh',
    'Tea': 'tea',
    'TeX': 'tex',
    'Text only': 'text',
    'Todotxt': 'todotxt',
    'Treetop': 'treetop',
    'Twig': 'twig',
    'TypeScript': 'ts',
    'UrbiScript': 'urbiscript',
    'Vala': 'vala',
    'VB.net': 'vb.net',
    'VCTreeStatus': 'vctreestatus',
    'Velocity': 'velocity',
    'verilog': 'verilog',
    'VGL': 'vgl',
    'vhdl': 'vhdl',
    'VimL': 'vim',
    'XML': 'xml',
    'XML+Cheetah': 'xml+cheetah',
    'XML+Django/Jinja': 'xml+django',
    'XML+Evoque': 'xml+evoque',
    'XML+Lasso': 'xml+lasso',
    'XML+Mako': 'xml+mako',
    'XML+Myghty': 'xml+myghty',
    'XML+PHP': 'xml+php',
    'XML+Ruby': 'xml+erb',
    'XML+Smarty': 'xml+smarty',
    'XML+Velocity': 'xml+velocity',
    'XQuery': 'xquery',
    'XSLT': 'xslt',
    'Xtend': 'xtend',
    'XUL+mozpreproc': 'xul+mozpreproc',
    'YAML': 'yaml',
    'YAML+Jinja': 'yaml+jinja',
    'Zephir': 'zephir',
}


def paste(content, expiry_days, syntax):
    """Make a paste to paste.ofcode.org."""
    response = requests.post(
        'http://paste.ofcode.org/',
        data={
            'code': content,
            'language': syntax,
            'notabot': 'most_likely',
        },
        headers={'User-Agent': USER_AGENT},
    )
    response.raise_for_status()
    return response.url
